@startuml
left to right direction

actor "Cliente" as cliente
actor "Restaurante" as restaurante

rectangle "Sistema Reserva Gourmet" {
    usecase "Cadastrar-se" as UC01
    usecase "Fazer Login" as UC02
    usecase "Buscar Restaurantes" as UC03
    usecase "Fazer Reserva" as UC04
    usecase "Gerenciar Reservas" as UC05
    usecase "Cadastrar Restaurante" as UC06
    usecase "Gerenciar Disponibilidade" as UC07
    usecase "Gerenciar Reservas Recebidas" as UC08
    usecase "Gerenciar Cardápio" as UC09
    usecase "Validar Dados" as UC10
    usecase "Enviar Notificação" as UC11
}

' Relacionamentos do Cliente
cliente -- UC01
cliente -- UC02
cliente -- UC03
cliente -- UC04
cliente -- UC05

' Relacionamentos do Restaurante
restaurante -- UC06
restaurante -- UC02
restaurante -- UC07
restaurante -- UC08
restaurante -- UC09


' Relacionamentos include
UC01 ..> UC10 : <<include>>
UC04 ..> UC10 : <<include>>
UC04 ..> UC11 : <<include>>
UC05 ..> UC11 : <<include>>
UC02 ..> UC10 : <<include>>
UC07 ..> UC11 : <<include>>

@enduml
